services:
  imgenie_app:
    image: imgenx:latest
    container_name: imgenie
    devices:
      - /dev/kfd
      - /dev/dri
    volumes:
      - .:/IMGENIE
      - /home/bharath/.imgenie:/root/.imgenie
      - /home/bharath/.cache/huggingface:/root/.cache/huggingface
    # working_dir: /IMGENIE
    # dns:
    #   - 8.8.8.8
    #   - 8.8.4.4
    ports:
      - "8000:8000"
    network_mode: host
    environment:
      - PYTORCH_ALLOC_CONF=expandable_segments:True
      - TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1
    # command: uvicorn imgen.server:app --host 0.0.0.0 --port 8000
    command: bash
    stdin_open: true
    tty: true

volumes:
  huggingface_cache:
    driver: local
