root_dir: "/root/.imgenie"
input_path: "input"
output_path: "output"

txt2img:
  ZImageTurbo:
    id: "zimage_turbo"
    name: "ZImage Turbo"
    description: "Text-to-Image generation with ZImage model"
    model_path: "models/TongyiMAI.ZImageTurbo"
    prompts_yaml: "prompts/prompts.yaml"
    lora_path: "loras"
    resolution_options: ["720x720", "1024x720", "1024x1024"]

img2txt:
  JoyCaption:
    id: "joy_caption"
    name: "Joy Caption"
    description: "Image-to-Text description with JoyCaption model"
    model_path: "models/fancyfeast.joycaption"
    input_path: "input"
    output_path: "output"
    threshold: 0.3
    system_prompt: "You are a helpful image captioner."
    max_new_tokens: 512
    temperature: 0.6
    top_p: 0.9

